project:
  type: website

website:
  title: "Midsprint"
  cookie-consent:
    style: simple
    palette: light
    type: implied
  page-navigation: true
  favicon: "images/midsprint-logo.png"
  google-analytics: "G-QGHEY0VBEL"
  
  navbar:
    title: false
    search: true
    pinned: true
    logo: "images/midsprint-logo-white.png"
    collapse: true
    left:
      - icon: house-fill
        href: index.qmd
        aria-label: Home
        text: "Home"
      - text: "About"
        href: "#about"
      - text: "Services"
        href: "#services"
      - text: "Contact"
        href: "#contact"
      - text: "Blog" 
        file: blog/index.qmd
    right: 
      - icon: twitter
        href: https://twitter.com/aaronzpearson
        aria-label: Twitter
      - icon: github
        href: https://github.com/aaronzpearson
        aria-label: Github
        
  sidebar:
  
    - id: blog
      title: "Blog"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - text: "**Blog Posts**"
          href: blog/index.qmd
        # - text: "Caloric Expenditure During a Marathon"
        #   href: blog/marathon-kcal-expend.qmd
        # - text: "Identifying the Lactate Threshold"
        #   href: blog/la-threshold.qmd
        - text: "Replicating Asymmetries vs Performance"
          href: blog/asym-vs-performance.qmd
        - text: "Review: Critical Velocity"
          href: blog/critical-speed.qmd
        - text: "Profiling Multiple Athletes with fvp"
          href: blog/fvp-split-apply-combine.qmd
        - text: "Big Data Bowl 2022 Submission"
          href: blog/bdb-22.qmd
        - text: "Modelling D' Balance Presentation"
          href: blog/d-prime-balance-presentation.qmd
        # - text: "Modelling Cardiac Drift"
        #   href: blog/cardiac-drift.qmd
        # - text: "Cleaning Catapult Data"
        #   href: blog/clean-catapult-data.qmd
        - text: "Big Data Bowl 2021 Submission"
          href: blog/bdb-21.qmd
        - text: "Fatigue Detection via Tracking Data Presentation"
          href: blog/fatigue-detection-presentation.qmd
          
    - title: " "
        
    
    
  page-footer: 
    border: false
    left: "Copyright 2022, Midsprint Sports Science Consulting"
    right: 
    - text: "Disclaimer"
      href: disclaimer.qmd
    - icon: twitter
      href: https://twitter.com/aaronzpearson
    - icon: github
      href: https://github.com/aaronzpearson
    - icon: envelope-fill
      href: mailto:aaron@midsprint.io
  twitter-card: true
  open-graph: true


format:
  html:
    smooth-scroll: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    fontsize: large
    code-copy: true