---
title: "Disclaimer"
---

Last updated September, 2022

## WEBSITE DISCLAIMER
The information provided by
Midsprint Sports Science Consulting ("we," "us," or "our") on https://midsprint.io (the "Site") is for general informational purposes only. All information on the Site is provided in good faith, however we make norepresentation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability,availability, or completeness of any information on the Site. UNDER NO CIRCUMSTANCE SHALL WE HAVE ANYLIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SITE OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SITE. YOUR USE OF THE SITE AND YOURRELIANCE ON ANY INFORMATION ON THE SITE IS SOLELY AT YOUR OWN RISK. 

## EXTERNAL LINKS DISCLAIMER 
The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originatingfrom third parties or links to websites and features in banners or other advertising. Such external links are notinvestigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. WE DONOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITYOF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE OR ANY WEBSITE OR FEATURE LINKED IN ANY BANNER OR OTHER ADVERTISING. WE WILL NOT BE A PARTY TO OR IN ANY WAYBE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OFPRODUCTS OR SERVICES. 

## PROFESSIONAL DISCLAIMER
The Site cannot and does not contain fitness advice. The fitness information is provided for general informational andeducational purposes only and is not a substitute for professional advice. Accordingly, before taking any actions basedupon such information, we encourage you to consult with the appropriate professionals. We do not provide any kind of fitness advice. THE USE OR RELIANCE OF ANY INFORMATION CONTAINED ON THE SITE IS SOLELY AT YOUROWN RISK.

## AFFILIATES DISCLAIMER
The Site may contain links to affiliate websites, and we receive an affiliate commission for any purchases made by you on the affiliate website using such links. Our affiliates may include the following:    
AvantLink    
Awin (Affiliate Window)    
CJ Affiliate by Conversant    
Clickbank    
eBay Partner Network    
FlexOffers    
iDevAffiliate    
MaxBounty    
Rakuten Affiliate Network    
RevenueWire    
ShareASale    
Refersion    

We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed toprovide a means for us to earn advertising fees by linking to Amazon.com and affiliated websites.